### ISSUE TITLE
Setup end to end testing

### ISSUE THREAD

**Issue by imranariffin** [imranariffin/small-steps#47]
Some viable options to look into:
1. [Appium](https://github.com/appium/appium)
2. [Detox](https://github.com/wix/Detox)

**Comment by vuggg** [comment]
I am getting Invalid regular expression error while running `npx react-native start`
```
error Invalid regular expression: /(.*\\__fixtures__\\.*|node_modules[\\\]react[\\\]dist[\\\].*|website\\node_modules\\.*|heapCapture\\bundle\.js|.*\\__tests__\\.*)$/: Unterminated character class. Run CLI with --verbose flag for more details.
SyntaxError: Invalid regular expression: /(.*\\__fixtures__\\.*|node_modules[\\\]react[\\\]dist[\\\].*|website\\node_modules\\.*|heapCapture\\bundle\.js|.*\\__tests__\\.*)$/: Unterminated character class
    at new RegExp (<anonymous>)
    at blacklist (C:\Users\think\Documents\PROJECT\Mobile-courses\small-steps-develop\node_modules\metro-config\src\defaults\blacklist.js:34:10)
    at getBlacklistRE (C:\Users\think\Documents\PROJECT\Mobile-courses\small-steps-develop\node_modules\@react-native-community\cli\build\tools\loadMetroConfig.js:69:59)
    at getDefaultConfig (C:\Users\think\Documents\PROJECT\Mobile-courses\small-steps-develop\node_modules\@react-native-community\cli\build\tools\loadMetroConfig.js:84:20)
    at load (C:\Users\think\Documents\PROJECT\Mobile-courses\small-steps-develop\node_modules\@react-native-community\cli\build\tools\loadMetroConfig.js:112:25)
    at Object.runServer [as func] (C:\Users\think\Documents\PROJECT\Mobile-courses\small-steps-develop\node_modules\@react-native-community\cli\build\commands\server\runServer.js:82:58)
    at Command.handleAction (C:\Users\think\Documents\PROJECT\Mobile-courses\small-steps-develop\node_modules\@react-native-community\cli\build\cliEntry.js:160:21)
    at Command.listener (C:\Users\think\Documents\PROJECT\Mobile-courses\small-steps-develop\node_modules\commander\index.js:315:8)
    at Command.emit (events.js:223:5)
    at Command.parseArgs (C:\Users\think\Documents\PROJECT\Mobile-courses\small-steps-develop\node_modules\commander\index.js:651:12)```


```
System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz
    Memory: 1.82 GB / 7.88 GB
  Binaries:
    Node: 12.14.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.17.3 - C:\Users\think\AppData\Roaming\npm\yarn.CMD
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5791312
```

While running yanr test:

```
yarn run v1.17.3
$ NODE_ICU_DATA=node_modules/full-icu/jest
'NODE_ICU_DATA' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
